#!/bin/bash
if [ $# != 2 ] ; then
echo "USAGE: cfc-auto-build \$ImageName \$DockerfilePath" 
exit 255
fi

imagename=$1
dockerfile=$2

podnamespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

regkey=$(kubectl get secret --namespace=$podnamespace | grep .registrykey | awk '{print $1}' | awk '{print $1}')

secert=$(kubectl get secret $regkey --namespace=$podnamespace -o yaml | grep .dockercfg: | awk '{print $2}')

keys=$(echo $secert | base64 -d)

username=$(echo $keys | jq '."https://master.cfc:8500".username')

password=$(echo $keys | jq '."https://master.cfc:8500".password')


docker build --rm -t $imagename $dockerfile || exit 255

docker tag $imagename  master.cfc:8500/$podnamespace/$imagename || exit 255

docker login -u ${username:1:-1} -p ${password:1:-1} -e ibm.com master.cfc:8500 || exit 255

docker push master.cfc:8500/$podnamespace/$imagename || exit 255
