#!/bin/bash

if [ $# != 1 ] ; then
echo "USAGE: cfc-auto-helm-k8s \$ChartName"
exit 255
fi

chartname=$1

export HELM_HOST=helm.kube-system:44134

podnamespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

helm-2.1.3 init --client-only || exit 255

helm-2.1.3 lint --strict $chartname || exit 255

helm-2.1.3 install $chartname --namespace $podnamespace || exit 255
